diff --git a/Makefile b/Makefile
index 470ac86..81aeb30 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,11 @@ dist: clean
 
 install: st
 	mkdir -p $(DESTDIR)$(PREFIX)/bin
-	cp -f st $(DESTDIR)$(PREFIX)/bin
+	cp -f st $(DESTDIR)$(PREFIX)/bin/st-bin
+	chmod 755 $(DESTDIR)$(PREFIX)/bin/st-bin
+	echo '#!/bin/sh'                       > $(DESTDIR)$(PREFIX)/bin/st
+	echo 'export BAT_THEME=gruvbox-light' >> $(DESTDIR)$(PREFIX)/bin/st
+	echo '$$(dirname "$$0")/st-bin'       >> $(DESTDIR)$(PREFIX)/bin/st
 	chmod 755 $(DESTDIR)$(PREFIX)/bin/st
 	mkdir -p $(DESTDIR)$(MANPREFIX)/man1
 	sed "s/VERSION/$(VERSION)/g" < st.1 > $(DESTDIR)$(MANPREFIX)/man1/st.1
@@ -52,6 +56,7 @@ install: st
 
 uninstall:
 	rm -f $(DESTDIR)$(PREFIX)/bin/st
+	rm -f $(DESTDIR)$(PREFIX)/bin/st-bin
 	rm -f $(DESTDIR)$(MANPREFIX)/man1/st.1
 
 .PHONY: all options clean dist install uninstall
